{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.service_cms }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "cms" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: cms
    port: {{ tuple "cms" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.cms.node_port.enabled }}
    nodePort: {{ .Values.network.cms.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.cms.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.cms.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}

{{- if .Values.manifests.service_fms }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "fms" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: fms
    port: {{ tuple "fms" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.fms.node_port.enabled }}
    nodePort: {{ .Values.network.fms.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.fms.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.fms.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}

{{- if .Values.manifests.service_ims }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "ims" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: ims
    port: {{ tuple "ims" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.ims.node_port.enabled }}
    nodePort: {{ .Values.network.ims.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.ims.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.ims.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}
{{- if .Values.manifests.service_rms }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "rms" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: rms
    port: {{ tuple "rms" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.rms.node_port.enabled }}
    nodePort: {{ .Values.network.rms.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.rms.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.rms.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}
{{- if .Values.manifests.service_rds }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "rds" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: rds
    port: {{ tuple "rds" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.rds.node_port.enabled }}
    nodePort: {{ .Values.network.rds.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.rds.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.rds.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}
{{- if .Values.manifests.service_uuid }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "uuid" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: uuid
    port: {{ tuple "uuid" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.uuid.node_port.enabled }}
    nodePort: {{ .Values.network.uuid.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.uuid.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.uuid.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}
{{- if .Values.manifests.service_audit }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "audit" "internal" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
spec:
  ports:
  - name: audit
    port: {{ tuple "audit" "internal" "api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
    {{- if .Values.network.audit.node_port.enabled }}
    nodePort: {{ .Values.network.audit.node_port.port }}
    {{ end }}
  selector:
{{ tuple $envAll "ranger" "ranger" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{ if .Values.network.audit.node_port.enabled }}
  type: NodePort
  {{- if .Values.network.audit.external_policy_local }}
  externalTrafficPolicy: Local
  {{ end }}
  {{ end }}
{{- end }}

