apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-mysql-thresh-secret"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
type: Opaque
data:
  username: {{ b64enc .Values.mysql.users.thresh.username | quote }}
  password: {{ b64enc .Values.mysql.users.thresh.password | quote }}
